const NewsActionTypes = {
    FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
    FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
    FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
    SET_PAGE_URL: "SET_PAGE_URL",
    SET_COUNTRY: "SET_COUNTRY",
}

export default NewsActionTypes;